
#create user
POST http://localhost:8000/api/auth/register
Content-Type: application/json

{
    "username": "user1",
    "password": "password",
    "email": "test1@email.com"
}

###
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "password"
}
