

#create user
POST http://localhost:8000/auth/registerUser/register
Content-Type: application/json

{
    "username": "pers233155333",
    "password": "password",
    "email": "dariosloique@gmail.com"
}


###
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "username": "pers2331333",
  "password": "$2a$10$JiDmneGsbtb0iNpzkWfcZeJ9e9eus6oDWd9wO3LTkcBdtLwH0ckkW"
}