version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  build:
    context: .
    dockerfile: Dockerfile.minio
  expose:
    - "9000"
    - "9001"
  #environment:
   # MINIO_ROOT_USER: 4M7rgN40Zj9PPQpIlRD2
    #MINIO_ROOT_PASSWORD: nszYImXnaaDgZVxlgRgJIZtMDetpQUBXtB0O9HTR
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5

services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
       
  db-user:
    container_name: hostit-db-user
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: hostit_user
    volumes:
      - data-mariadb-user:/var/lib/mysql
  
  db-storage:
    container_name: hostit-db-storage
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: hostit_storage
    volumes:
      - data-mariadb-storage:/var/lib/mysql
  
  api-user:
    container_name: hostit-api-user
    image: haroldraj/hostit-user:1.1.0
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db-user:3306/hostit_user
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      MINIO_HOST_IP_ADDRESS: 192.168.129.101
    depends_on:
      - db-user
    ports:
      - "8002:8002"
  
  api-storage:
    container_name: hostit-api-storage
    image: haroldraj/hostit-storage:1.1.0
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db-storage:3306/hostit_storage
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8001:8001"
    depends_on:
      - nginx
      - api-user
      - db-storage

volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
  data-mariadb-storage:
  data-mariadb-user:
