### GET request to example server
GET https://219d-2a02-a03f-682e-3901-55bb-1e40-ce91-35e9.ngrok-free.app/api/storage/file/all/files
###
GET https://219d-2a02-a03f-682e-3901-55bb-1e40-ce91-35e9.ngrok-free.app/api/storage/file/all/files
###
GET https://219d-2a02-a03f-682e-3901-55bb-1e40-ce91-35e9.ngrok-free.app/api/storage/folder/foldercontents?folderName=My Hostit&userId=1