minio:
  image: bitnami/minio:2021.3.1
  container_name: minio
  environment:
    MINIO_ACCESS_KEY: "Q3AM3UQ867SPQQA43P2F"
    MINIO_SECRET_KEY: "tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
  volumes:

  ./data/minio-persistence:/data
  ./data/minio-persistence/certs:/certs
ports:
  9000:9000