
#create user
POST http://localhost:8002/api/auth/register
Content-Type: application/json

{
    "username": "haroldraja",
    "password": "password",
    "email": "haroldraja@email.com"
}

###
POST https://a1e152503d2492b864414204ba9d4f47.loophole.site/api/auth/login
Content-Type: application/json

{
  "username": "haroldraja",
  "password": "password"
}
